### Generate a new code
POST http://127.0.0.1:5000/generate_code
Content-Type: application/json

{
  "order_id": "einar12",
  "usage_limit": 3
}

### Get all codes in the database
GET http://127.0.0.1:5000/admin/codes

### Get the last N created codes
GET http://127.0.0.1:5000/admin/codes/last/<COUNT>

### Get all codes for a specific order ID
GET http://127.0.0.1:5000/admin/codes/by_order_id/<ORDER_ID>

### Get info about a specific code
GET http://127.0.0.1:5000/admin/codes/<CODE>

### Delete a code by code
DELETE http://127.0.0.1:5000/admin/codes/<CODE>

### Delete all codes for an order ID
DELETE http://127.0.0.1:5000/admin/codes/by_order_id/<ORDER_ID>

### Update a setting
PUT http://127.0.0.1:5000/admin/settings/<SETTING_KEY>
Content-Type: application/json

{
  "value": "<NEW_VALUE>"
}

### Get all scan log entries for an order ID
GET http://127.0.0.1:5000/admin/usage/by_order_id/<ORDER_ID>

### Get all scan log entries for a code
GET http://127.0.0.1:5000/admin/usage/by_code/<CODE>

### Get the last N scan log entries
GET http://127.0.0.1:5000/admin/scan_logs/last/<COUNT>